apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: /homelab/monitoring/grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: /homelab/monitoring/grafana-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: alertmanager-discord
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: /homelab/monitoring/discord-webhook-url
    - secretKey: healthchecks-url
      remoteRef:
        key: /homelab/monitoring/healthchecks-watchdog-url
