apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: minecraft-secrets
    creationPolicy: Owner
  data:
    - secretKey: rcon-password
      remoteRef:
        key: /homelab/minecraft/rcon-password
