apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - namespace.yaml
  - externalsecrets.yaml
  - statefulset.yaml
  - platform.generated.yaml   # gerado por scripts/render-games.py
patches:
  - path: replicas.yaml       # gerado por scripts/switch-game.py
configMapGenerator:
  - name: minecraft-scripts
    files:
      - exporter.py=scripts/exporter.py
      - users.py=scripts/users.py
      - easyauth.py=scripts/easyauth.py
generatorOptions:
  disableNameSuffixHash: true
