apiVersion: v1
kind: Service
metadata:
  name: zomboid-metrics
  namespace: zomboid
  labels:
    app: zomboid-metrics
spec:
  clusterIP: None
  selector:
    app: zomboid
  ports:
    - name: metrics
      port: 9105
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zomboid
  namespace: zomboid
spec:
  selector:
    matchLabels:
      app: zomboid-metrics
  endpoints:
    - port: metrics
      interval: 30s
