apiVersion: v1
kind: Service
metadata:
  name: zomboid
  namespace: zomboid
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: zomboid
  ports:
    - name: game
      protocol: UDP
      port: 16261
      targetPort: 16261
    - name: direct
      protocol: UDP
      port: 16262
      targetPort: 16262
