apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zomboid-secrets
  namespace: zomboid
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: zomboid-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: /homelab/zomboid/admin-password
    - secretKey: server-password
      remoteRef:
        key: /homelab/zomboid/server-password
    - secretKey: rcon-password
      remoteRef:
        key: /homelab/zomboid/rcon-password
