apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraria-secrets
  namespace: terraria
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: terraria-secrets
    creationPolicy: Owner
  data:
    - secretKey: server-password
      remoteRef:
        key: /homelab/terraria/server-password
    - secretKey: rest-token
      remoteRef:
        key: /homelab/terraria/rest-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraria-backup
  namespace: terraria
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: terraria-backup
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: /homelab/backup/restic-repository
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: /homelab/backup/restic-password
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /homelab/backup/restic-aws-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /homelab/backup/restic-aws-secret-access-key
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: /homelab/backup/aws-region
