apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraria-secrets
  namespace: terraria
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: terraria-secrets
    creationPolicy: Owner
  data:
    - secretKey: server-password
      remoteRef:
        key: /homelab/terraria/server-password
    - secretKey: rest-token
      remoteRef:
        key: /homelab/terraria/rest-token
