apiVersion: v1
kind: Service
metadata:
  name: terraria
  namespace: terraria
  labels:
    app.kubernetes.io/name: terraria
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: terraria
  ports:
    - name: game
      port: 7777
      targetPort: game
      protocol: TCP
