apiVersion: v1
kind: Service
metadata:
  name: terraria
  namespace: terraria
  labels:
    app.kubernetes.io/name: terraria
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: terraria
  ports:
    - name: game
      port: 16261          # mesma porta externa do Zomboid (aqui em TCP; o Zomboid usa UDP)
      targetPort: game     # 7777 dentro do container
      protocol: TCP
